version: '3.4'

services:
  web:
    image: elment/authocto
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SERVER_PORT=${SERVER_PORT}
      # - REDIS_PORT=6379
      - REDIS_HOST=rediscache
      - URL=mongodb://db:27017/authocto
      - LIFETIME=${LIFETIME}
      - ENV=${ENV}
      - SESSION_NAME=${SESSION_NAME}
      - SESSION_SECRET=${SESSION_SECRET}
      - SESSION_LIFETIME=${SESSION_LIFETIME} 
      # NODE_ENV: development
    ports:
      - 5000:${SERVER_PORT}
    volumes: 
      - ./:/usr/src/app
    depends_on:
      - db
      - rediscache
    # command: ["./node_modules/nodemon/bin/nodemon.js", "-L", "app.js"]
  
  db:
    image: mongo:latest
    container_name: jwt-db
    ports:
      - 27017:27017
    volumes: 
      - mongodata:/data/db
  

  rediscache:
    image: elment/redis
    container_name: jwt-redis-db
    # ports:
      # - 6379:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD} 
    command: ["redis-server", "--requirepass","${REDIS_PASSWORD}"]
    volumes: 
      - redisdata:/data

volumes:
  mongodata:
  redisdata: